// <auto-generated />
namespace MasterApplication_SSluzbaMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RegisterForAnExam_Modifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegisterForAnExam_Modifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201806282302201_RegisterForAnExam_Modifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
